"""
api/routes/scan.py
Hybrid AI Red Team Scan API.

Starts the full pipeline in the background and exposes
the sessions generated by the pipeline itself.
"""

from fastapi import APIRouter, BackgroundTasks, HTTPException

from engine.modules.api.schemas import ScanRequest
from engine.main import run_pipeline

from backend.core.progress import update

from engine.database.repository import (
    get_all_sessions,
    get_session_by_id,
)


router = APIRouter(
    prefix="/api/scan",
    tags=["Scan"],
)


# ==========================================
# Background Pipeline Runner
# ==========================================

def execute_scan(
    target: str,
    lhost: str,
) -> None:
    """
    Run the full assessment pipeline.

    Important:
    run_pipeline() is the only component responsible
    for generating and saving the session ID.
    """

    try:
        update(
            0,
            "Initializing Assessment",
            0,
        )

        run_pipeline(
            target=target,
            lhost=lhost,
        )

        # لا نستدعي finish() هنا.
        # run_pipeline هو المسؤول عن تحديث آخر مرحلة
        # وحالة completion بعد إنشاء التقرير.

    except Exception as error:
        print(
            f"[Scan API] Pipeline failed: {error}"
        )

        update(
            0,
            f"Assessment Failed: {error}",
            0,
        )


# ==========================================
# Start Scan
# ==========================================

@router.post("/run")
async def run_scan(
    req: ScanRequest,
    background_tasks: BackgroundTasks,
):
    """
    Accept the request immediately and execute the
    pipeline as a FastAPI background task.
    """

    background_tasks.add_task(
        execute_scan,
        req.target,
        req.lhost,
    )

    return {
        "status": "started",
        "target": req.target,
        "lhost": req.lhost,
        "message": (
            "Security assessment started successfully."
        ),
    }


# ==========================================
# Sessions
# ==========================================

@router.get("/sessions")
def sessions():
    data = get_all_sessions()

    return {
        "sessions": data,
        "count": len(data),
    }


@router.get("/sessions/{session_id}")
def session(
    session_id: str,
):
    result = get_session_by_id(
        session_id
    )

    if not result:
        raise HTTPException(
            status_code=404,
            detail="Session not found",
        )

    return result
