"""
heatmap_generator.py  —  ATT&CK Navigator Layer JSON Generator
Produces a valid Navigator 4.9 layer importable at:
  https://mitre-attack.github.io/attack-navigator/
"""

import json
import os
from datetime import datetime

COLOR_MAP = {
    "rule_exact":    "#e03d3d",   # red   — high confidence rule
    "rule_service":  "#e07d00",   # orange
    "rule_cve":      "#e07d00",
    "post_exploit":  "#34d399",   # green
    "stix":          "#c0882a",   # amber
    "ml":            "#3b82f6",   # blue
    "ml_fallback":   "#6b7280",   # gray
}

SCORE_MAP = {
    "rule_exact":   100,
    "rule_service":  80,
    "rule_cve":      80,
    "post_exploit":  95,
    "stix":          65,
    "ml":            55,
    "ml_fallback":   40,
}


class HeatmapGenerator:

    def generate(self, mapped_results: list[dict]) -> dict:
        """Return ATT&CK Navigator layer dict."""
        techniques_seen: dict[str, dict] = {}

        for result in mapped_results:
            for layer_result in result.get("layers", []):
                tid    = layer_result.get("technique_id", "")
                source = layer_result.get("source", "ml_fallback")

                # Skip pseudo IDs from ML fallback
                if not tid or tid.startswith("T-"):
                    continue

                score = SCORE_MAP.get(source, 40)
                color = COLOR_MAP.get(source, "#6b7280")
                conf  = layer_result.get("confidence", 0.5)

                if tid not in techniques_seen or score > techniques_seen[tid]["score"]:
                    techniques_seen[tid] = {
                        "techniqueID": tid,
                        "score":       score,
                        "color":       color,
                        "comment":     (
                            f"Source: {source} | "
                            f"Confidence: {conf:.0%} | "
                            f"Host: {result.get('host', '')}"
                        ),
                        "enabled":     True,
                        "metadata":    [],
                        "links":       [],
                        "showSubtechniques": False,
                    }

        layer = {
            "name":            "Red Team AI — Hybrid ATT&CK Layer",
            "versions":        {"attack": "14", "navigator": "4.9", "layer": "4.5"},
            "domain":          "enterprise-attack",
            "description":     f"Generated by Hybrid Red Team AI Framework — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "filters":         {"platforms": ["Linux", "Windows", "macOS"]},
            "sorting":         3,
            "layout":          {"layout": "side", "aggregateFunction": "average",
                                "showID": True, "showName": True},
            "hideDisabled":    False,
            "techniques":      list(techniques_seen.values()),
            "gradient": {
                "colors": ["#ffffff", "#e03d3d"],
                "minValue": 0,
                "maxValue": 100,
            },
            "legendItems": [
                {"label": "Rule-based (0.85–0.95)", "color": "#e03d3d"},
                {"label": "STIX semantic (0.60–0.75)", "color": "#c0882a"},
                {"label": "ML classifier (0.50–0.70)", "color": "#3b82f6"},
                {"label": "Post-exploitation", "color": "#34d399"},
            ],
            "metadata": [],
            "links":    [],
            "showTacticRowBackground": True,
            "tacticRowBackground": "#1a2235",
        }

        print(f"  [Heatmap] {len(techniques_seen)} technique(s) mapped to Navigator layer.")
        return layer

    def save(self, layer: dict, path: str):
        os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(layer, f, indent=2, ensure_ascii=False)
        print(f"  [Heatmap] Layer saved → {path}")
